name: App-tier CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Docker Image
        run: |
          docker build -t app-tier .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy with SSH (Debug Enabled)
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.APP_TIER_EC2_HOST }}
          username: ${{ secrets.APP_TIER_EC2_USERNAME }}
          key: ${{ secrets.APP_TIER_EC2_PRIVATE_KEY }}
          script: |
            echo "Pulling Docker images..."
            docker pull abhimonk1998/web-tier:latest

            echo "Stopping and removing existing containers..."
            docker stop web-tier || true
            docker rm web-tier || true

            echo "Creating Docker network..."
            docker network create my-network || true

            echo "Starting web-tier container..."
            docker run -d --name web-tier --network my-network \
              -p 80:3000 \
              -v /path/to/data:/app/data \
              -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
              -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
              -e AWS_REGION=${{ secrets.AWS_REGION }} \
              ${{ secrets.DOCKER_USERNAME }}/web-tier:latest

          debug: true
